/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitalityvault;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextArea;

/**
 *
 * @author deand
 */
public class VVSignUpGUI extends javax.swing.JFrame {

    Connection myConn;

    /**
     * Creates new form VitalityVaultHomeGUI
     */
    public VVSignUpGUI() {
        initComponents();
        getConnection();
    }

    private void getConnection() {
        try {
            myConn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/foods", "dean_dolan", "temppassword");
        } catch (SQLException e) {
            System.out.println("Error connecting" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navPan = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        bodyPan = new javax.swing.JPanel();
        signInPan = new javax.swing.JPanel();
        signInLbl = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JTextField();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        navPan.setBackground(new java.awt.Color(0, 204, 204));

        titleLbl.setFont(new java.awt.Font("Verdana Pro Cond", 1, 40)); // NOI18N
        titleLbl.setText(" Vitality Vault");

        javax.swing.GroupLayout navPanLayout = new javax.swing.GroupLayout(navPan);
        navPan.setLayout(navPanLayout);
        navPanLayout.setHorizontalGroup(
            navPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navPanLayout.setVerticalGroup(
            navPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navPanLayout.createSequentialGroup()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bodyPan.setBackground(new java.awt.Color(0, 204, 204));

        signInLbl.setFont(new java.awt.Font("Verdana Pro", 1, 30)); // NOI18N
        signInLbl.setText("Sign Up/Login:");

        signUpBtn.setFont(new java.awt.Font("Verdana Pro", 1, 24)); // NOI18N
        signUpBtn.setText("Sign Up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Verdana Pro", 1, 24)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        usernameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTfActionPerformed(evt);
            }
        });

        passwordTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTfActionPerformed(evt);
            }
        });

        usernameLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usernameLbl.setText("Username");

        passwordLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passwordLbl.setText("Password");

        javax.swing.GroupLayout signInPanLayout = new javax.swing.GroupLayout(signInPan);
        signInPan.setLayout(signInPanLayout);
        signInPanLayout.setHorizontalGroup(
            signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPanLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(signUpBtn)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signInPanLayout.createSequentialGroup()
                .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(signInPanLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(signInLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, signInPanLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTf)
                            .addComponent(passwordTf))))
                .addGap(91, 91, 91))
        );
        signInPanLayout.setVerticalGroup(
            signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInPanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(signInLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLbl))
                .addGap(18, 18, 18)
                .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl))
                .addGap(46, 46, 46)
                .addGroup(signInPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginBtn)
                    .addComponent(signUpBtn))
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyPanLayout = new javax.swing.GroupLayout(bodyPan);
        bodyPan.setLayout(bodyPanLayout);
        bodyPanLayout.setHorizontalGroup(
            bodyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(signInPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        bodyPanLayout.setVerticalGroup(
            bodyPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signInPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        // Get the username and password from text fields
        String username = usernameTf.getText();
        String password = passwordTf.getText();

        if (!usernameTf.getText().isEmpty() && !passwordTf.getText().isEmpty()) {
            try (Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/foods", "dean_dolan", "temppassword")) {
                // Construct the SQL INSERT statement to add the new user
                String insertStatement = "INSERT INTO login_information (Username, Password) VALUES (?, ?)";
                try (PreparedStatement pstmt = myConn.prepareStatement(insertStatement)) {
                    pstmt.setString(1, usernameTf.getText());
                    pstmt.setString(2, passwordTf.getText());
                    pstmt.executeUpdate();

                    // Notify the user about successful sign up
                    System.out.println("User signed up successfully.");
                    VVSignUpGUI signup = new VVSignUpGUI();
                    signup.setVisible(false);
                    VVHomeGUI home = new VVHomeGUI();
                    home.setVisible(true);
                } catch (SQLException e) {
                    e.printStackTrace();
                    // Handle SQL exception
                }
                // Handle the case where either the username or password field is blank
                // For example, you could display an error message to the user
            } catch (SQLException ex) {
                Logger.getLogger(VVSignUpGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_signUpBtnActionPerformed


    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        // Get the username and password from text fields
        String username = usernameTf.getText();
        String password = passwordTf.getText();

        if (!username.isEmpty() && !password.isEmpty()) {
            try (Connection myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/foods", "dean_dolan", "temppassword")) {
                // Construct the SQL SELECT statement to check if the user exists
                String selectStatement = "SELECT * FROM login_information WHERE Username = ? AND Password = ?";
                try (PreparedStatement pstmt = myConn.prepareStatement(selectStatement)) {
                    pstmt.setString(1, username);
                    pstmt.setString(2, password);
                    try (ResultSet rs = pstmt.executeQuery()) {
                        // Check if any rows were returned
                        if (rs.next()) {
                            // Username and password match, navigate to home GUI
                            System.out.println("Logged in successfully.");
                            VVHomeGUI home = new VVHomeGUI();
                            home.setVisible(true);
                            // Close the current GUI
                            dispose();
                        } else {
                            // Username or password is incorrect
                            System.out.println("You have entered an incorrect username or password.");
                        }
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                    // Handle SQL exception
                }
            } catch (SQLException ex) {
                Logger.getLogger(VVSignUpGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            // Handle the case where either the username or password field is blank
            // For example, you could display an error message to the user
            System.out.println("Please enter both username and password.");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void usernameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTfActionPerformed
        // TODO add your handling code here:
        VVSignUp username = new VVSignUp();
        // username.setUsername(usernameTf.getText());
    }//GEN-LAST:event_usernameTfActionPerformed

    private void passwordTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTfActionPerformed
        // TODO add your handling code here:
        VVSignUp password = new VVSignUp();
        // password.setUsername(passwordTf.getText());
    }//GEN-LAST:event_passwordTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVSignUpGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVSignUpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPan;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel navPan;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTf;
    private javax.swing.JLabel signInLbl;
    private javax.swing.JPanel signInPan;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
