/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vitalityvault;

import javax.swing.JComboBox;

/**
 *
 * @author codyc
 */
public class vvworkout extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public vvworkout() {
        initComponents();
    }

    /*
    Object genderCB;
    public javax.swing.JComboBox<String> getGenderCB() {
        return (JComboBox<String>) genderCB;
    
    }
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        wedT = new javax.swing.JLabel();
        thuT = new javax.swing.JLabel();
        tueT = new javax.swing.JLabel();
        monT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        thuBox = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        wedBox = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tueBox = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        monBox = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        sunBox = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        satBox = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        friBox = new javax.swing.JTextArea();
        friT = new javax.swing.JLabel();
        satT = new javax.swing.JLabel();
        sunT = new javax.swing.JLabel();
        workBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        wedT.setText("Wednesday");

        thuT.setText("Thursday");

        tueT.setText("Tuesday");

        monT.setText("Monday");

        jLabel1.setText("Workout Plan");

        thuBox.setColumns(20);
        thuBox.setRows(5);
        jScrollPane3.setViewportView(thuBox);

        wedBox.setColumns(20);
        wedBox.setRows(5);
        jScrollPane2.setViewportView(wedBox);

        tueBox.setColumns(20);
        tueBox.setRows(5);
        jScrollPane1.setViewportView(tueBox);

        monBox.setColumns(20);
        monBox.setRows(5);
        jScrollPane5.setViewportView(monBox);

        sunBox.setColumns(20);
        sunBox.setRows(5);
        jScrollPane6.setViewportView(sunBox);

        satBox.setColumns(20);
        satBox.setRows(5);
        jScrollPane7.setViewportView(satBox);

        friBox.setColumns(20);
        friBox.setRows(5);
        jScrollPane4.setViewportView(friBox);

        friT.setText("Friday");

        satT.setText("Saturday");

        sunT.setText("Sunday");

        workBtn.setText("Get Workout");
        workBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Next ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<- Prev");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(friT, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(satT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sunT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton2)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(workBtn)
                                        .addGap(224, 224, 224)
                                        .addComponent(jButton1)))
                                .addGap(31, 31, 31))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(monT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tueT)
                        .addGap(138, 138, 138)
                        .addComponent(wedT)
                        .addGap(139, 139, 139)
                        .addComponent(thuT)
                        .addGap(67, 67, 67))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(thuT))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monT)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wedT)
                            .addComponent(tueT))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(friT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(satT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sunT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(workBtn)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VVCalTrackerGUI myGUI = new VVCalTrackerGUI();
        myGUI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        vvworkout closeGUI = new vvworkout();
        closeGUI.setVisible(false);
        VVHGUI myGUI = new VVHGUI();
        myGUI.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void workBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workBtnActionPerformed

        // Get the selected gender as a string
        VVHGUI g = new VVHGUI();

// Assuming x is a field in VVHGUI class to hold the gender selection
        String gender = (String) g.getGenderCB().getSelectedItem();
        String age = g.getAgeTF().getText();

// Parse age text into an integer
        int iAge = 0; // Default value for age
        if (!age.isEmpty()) {
            iAge = Integer.parseInt(age);
        }

// Check gender and age together
        if (Integer.parseInt(gender) == 1 && iAge < 40) {
            // Male specific workout plan for age < 40
            //System.out.println("old man");
                        monBox.append("Monday (Chest, Shoulders, Triceps):\n");
                        monBox.append("Chest:\n");
                        monBox.append("Bench Press: 3 sets x 8 reps\n");
                        monBox.append("Incline Dumbbell Press: 3 sets x 10 reps\n");
                        monBox.append("Shoulders:\n");
                        monBox.append("Dumbbell Shoulder Press: 3 sets x 10 reps\n");
                        monBox.append("Lateral Raises: 3 sets x 12 reps\n");
                        monBox.append("Triceps:\n");
                        monBox.append("Tricep Dips: 3 sets x 10 reps\n");
                        monBox.append("Overhead Tricep Extension: 3 sets x 12 reps\n\n");

                        tueBox.append("\nTuesday (Light Cardio):\n");
                        tueBox.append("Enjoy a light cardio session such as a 30-minute brisk walk or cycling.\n\n");

                        wedBox.append("\nWednesday (Back, Biceps):\n");
                        wedBox.append("Back:\n");
                        wedBox.append("Bent Over Rows: 3 sets x 8 reps\n");
                        wedBox.append("Lat Pulldowns: 3 sets x 10 reps\n");
                        wedBox.append("Biceps:\n");
                        wedBox.append("Barbell Curls: 3 sets x 10 reps\n");
                        wedBox.append("Hammer Curls: 3 sets x 12 reps\n\n");

                        thuBox.append("\nThursday (Rest):\n");
                        thuBox.append("Take this day to rest and allow your muscles to recover.\n\n");

                        friBox.append("\nFriday (Legs):\n");
                        friBox.append("Legs:\n");
                        friBox.append("Squats: 3 sets x 8 reps\n");
                        friBox.append("Lunges: 3 sets x 10 reps each leg\n");
                        friBox.append("Leg Press: 3 sets x 12 reps\n");
                        friBox.append("Calf Raises: 3 sets x 15 reps\n\n");

                        satBox.append("\nSaturday (Light Cardio):\n");
                        satBox.append("Engage in another light cardio session, such as a 30-minute walk or swimming.\n\n");

                        sunBox.append("\nSunday (Rest):\n");
                        sunBox.append("Take a well-deserved rest day to relax and rejuvenate.\n");
        } else if (Integer.parseInt(gender) == 1 && iAge >= 40) {
            // Male specific workout plan for age >= 40
                        monBox.append("Monday (Chest, Shoulders, Triceps):\n");
                        monBox.append("Chest:\n");
                        monBox.append("Bench Press: 4 sets x 8 reps\n");
                        monBox.append("Incline Dumbbell Press: 3 sets x 10 reps\n");
                        monBox.append("Shoulders:\n");
                        monBox.append("Military Press: 4 sets x 8 reps\n");
                        monBox.append("Lateral Raises: 3 sets x 12 reps\n");
                        monBox.append("Triceps:\n");
                        monBox.append("Tricep Dips: 3 sets x 10 reps\n");
                        monBox.append("Skull Crushers: 3 sets x 10 reps\n\n");

                        tueBox.append("\nTuesday (Back, Biceps):\n");
                        tueBox.append("Back:\n");
                        tueBox.append("Deadlifts: 4 sets x 8 reps\n");
                        tueBox.append("Pull-Ups: 3 sets x 10 reps\n");
                        tueBox.append("Biceps:\n");
                        tueBox.append("Barbell Curls: 3 sets x 10 reps\n");
                        tueBox.append("Preacher Curls: 3 sets x 10 reps\n\n");

                        wedBox.append("\nWednesday (Legs, Abs):\n");
                        wedBox.append("Legs:\n");
                        wedBox.append("Squats: 4 sets x 8 reps\n");
                        wedBox.append("Leg Press: 3 sets x 10 reps\n");
                        wedBox.append("Abs:\n");
                        wedBox.append("Planks: 3 sets x 1 minute\n");
                        wedBox.append("Russian Twists: 3 sets x 15 reps\n\n");

                        thuBox.append("\nThursday (HIIT Cardio):\n");
                        thuBox.append("High-Intensity Interval Training (HIIT):\n");
                        thuBox.append("30 seconds sprint followed by 2 minutes walk x 6 sets\n\n");

                        friBox.append("\nFriday (Chest, Back):\n");
                        friBox.append("Chest:\n");
                        friBox.append("Incline Bench Press: 4 sets x 8 reps\n");
                        friBox.append("Dumbbell Flyes: 3 sets x 10 reps\n");
                        friBox.append("Back:\n");
                        friBox.append("Barbell Rows: 4 sets x 8 reps\n");
                        friBox.append("Lat Pulldowns: 3 sets x 10 reps\n\n");

                        satBox.append("\nSaturday (Shoulders, Arms):\n");
                        satBox.append("Shoulders:\n");
                        satBox.append("Seated Dumbbell Press: 4 sets x 8 reps\n");
                        satBox.append("Front Raises: 3 sets x 10 reps\n");
                        satBox.append("Arms:\n");
                        satBox.append("Tricep Pushdowns: 3 sets x 10 reps\n");
                        satBox.append("Hammer Curls: 3 sets x 10 reps\n\n");

                        sunBox.append("\nSunday (Rest):\n");
                        sunBox.append("Enjoy a well-deserved rest day!\n");
        } else if (Integer.parseInt(gender) == 2 && iAge < 40) {
            // Female specific workout plan for age < 40
                        monBox.append("Monday (Chest, Shoulders, Triceps):\n");
                        monBox.append(" Chest:\n Bench Press - 3 sets x 10 reps\n Push-Ups - 3 sets x 10 reps\n\n");
                        monBox.append(" Shoulders:\n Dumbbell Shoulder Press - 3 sets x 10 reps\n Lateral Raises - 3 sets x 12 reps\n\n");
                        monBox.append(" Triceps:\n Tricep Dips - 3 sets x 10 reps\n Overhead Triceps Extensions - 3 sets x 12 reps\n\n");

                        tueBox.append("\nTuesday (Light Cardio - 1hr Walk):\n");
                        tueBox.append(" Enjoy a brisk 1-hour walk, maintaining a pace that raises your heart rate but allows for comfortable conversation.\n\n");

                        wedBox.append("\nWednesday (Back, Biceps):\n");
                        wedBox.append(" Back:\n Bent Over Rows - 3 sets x 10 reps\n Lat Pulldowns - 3 sets x 10 reps\n");
                        wedBox.append(" Biceps:\n Bicep Curls (with dumbbells) - 3 sets x 10 reps\n Hammer Curls - 3 sets x 12 reps\n\n");

                        thuBox.append("\nThursday (Rest):\n");
                        thuBox.append(" Take this day to relax and allow your muscles to recover.\n\n");

                        friBox.append("\nFriday (Legs):\n");
                        friBox.append(" Legs:\n Squats - 3 sets x 10 reps\n Lunges - 3 sets x 10 reps each leg\n Leg Press - 3 sets x 12 reps\n Calf Raises - 3 sets x 15 reps\n\n");

                        satBox.append("\nSaturday (Light Cardio - 1hr Walk):\n");
                        satBox.append(" Another 1-hour walk at a comfortable pace to keep your body active.\n\n");

                        sunBox.append("\nSunday (Rest):\n");
                        sunBox.append(" Another day for rest and recovery.\n");
        } else if (Integer.parseInt(gender) == 2 && iAge >= 40) {
            // Female specific workout plan for age >= 40
            System.out.println("leng");
                        monBox.append("Monday (Chest, Shoulders, Triceps):\n");
                        monBox.append(" Chest:\n Bench Press - 3 sets x 10 reps\n Push-Ups - 3 sets x 10 reps\n\n");
                        monBox.append(" Shoulders:\n Dumbbell Shoulder Press - 3 sets x 10 reps\n Lateral Raises - 3 sets x 12 reps\n\n");
                        monBox.append(" Triceps:\n Tricep Dips - 3 sets x 10 reps\n Overhead Triceps Extensions - 3 sets x 12 reps\n\n");

                        tueBox.append("\nTuesday (Light Cardio - 1hr Walk):\n");
                        tueBox.append(" Enjoy a brisk 1-hour walk, maintaining a pace that raises your heart rate but allows for comfortable conversation.\n\n");

                        wedBox.append("\nWednesday (Back, Biceps):\n");
                        wedBox.append(" Back:\n Bent Over Rows - 3 sets x 10 reps\n Lat Pulldowns - 3 sets x 10 reps\n");
                        wedBox.append(" Biceps:\n Bicep Curls (with dumbbells) - 3 sets x 10 reps\n Hammer Curls - 3 sets x 12 reps\n\n");

                        thuBox.append("\nThursday (Rest):\n");
                        thuBox.append(" Take this day to relax and allow your muscles to recover.\n\n");

                        friBox.append("\nFriday (Legs):\n");
                        friBox.append(" Legs:\n Squats - 3 sets x 10 reps\n Lunges - 3 sets x 10 reps each leg\n Leg Press - 3 sets x 12 reps\n Calf Raises - 3 sets x 15 reps\n\n");

                        satBox.append("\nSaturday (Light Cardio - 1hr Walk):\n");
                        satBox.append(" Another 1-hour walk at a comfortable pace to keep your body active.\n\n");

                        sunBox.append("\nSunday (Rest):\n");
                        sunBox.append(" Another day for rest and recovery.\n");

                    } else {
                        // Higher intensity workout for young woman
                        monBox.append("Monday (Legs, Abs):\n");
                        monBox.append("Legs:\n");
                        monBox.append("Squats: 3 sets x 10 reps\n");
                        monBox.append("Lunges: 3 sets x 10 reps each leg\n");
                        monBox.append("Leg Press: 3 sets x 12 reps\n");
                        monBox.append("Abs:\n");
                        monBox.append("Planks: 3 sets x 1 minute\n");
                        monBox.append("Russian Twists: 3 sets x 15 reps\n\n");

                        tueBox.append("\nTuesday (Chest, Shoulders, Triceps):\n");
                        tueBox.append("Chest:\n");
                        tueBox.append("Push-Ups: 3 sets x 10 reps\n");
                        tueBox.append("Dumbbell Bench Press: 3 sets x 10 reps\n");
                        tueBox.append("Shoulders:\n");
                        tueBox.append("Dumbbell Shoulder Press: 3 sets x 10 reps\n");
                        tueBox.append("Lateral Raises: 3 sets x 12 reps\n");
                        tueBox.append("Triceps:\n");
                        tueBox.append("Tricep Dips: 3 sets x 10 reps\n");
                        tueBox.append("Tricep Kickbacks: 3 sets x 12 reps\n\n");

                        wedBox.append("\nWednesday (Back, Biceps):\n");
                        wedBox.append("Back:\n");
                        wedBox.append("Deadlifts: 3 sets x 10 reps\n");
                        wedBox.append("Bent Over Rows: 3 sets x 10 reps\n");
                        wedBox.append("Biceps:\n");
                        wedBox.append("Barbell Curls: 3 sets x 10 reps\n");
                        wedBox.append("Hammer Curls: 3 sets x 12 reps\n\n");

                        thuBox.append("\nThursday (HIIT Cardio):\n");
                        thuBox.append("High-Intensity Interval Training (HIIT):\n");
                        thuBox.append("30 seconds sprint followed by 2 minutes walk x 6 sets\n\n");

                        friBox.append("\nFriday (Glutes, Hamstrings):\n");
                        friBox.append("Glutes:\n");
                        friBox.append("Glute Bridges: 3 sets x 12 reps\n");
                        friBox.append("Donkey Kicks: 3 sets x 12 reps each leg\n");
                        friBox.append("Hamstrings:\n");
                        friBox.append("Romanian Deadlifts: 3 sets x 10 reps\n");
                        friBox.append("Hamstring Curls: 3 sets x 12 reps\n\n");

                        satBox.append("\nSaturday (Rest):\n");
                        satBox.append("Take a day off to allow your body to rest and recover.\n\n");

                        sunBox.append("\nSunday (Yoga):\n");
                        sunBox.append("Engage in a relaxing yoga session to stretch and unwind.\n");
        }


    }//GEN-LAST:event_workBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vvworkout.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vvworkout.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vvworkout.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vvworkout.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vvworkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea friBox;
    private javax.swing.JLabel friT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea monBox;
    private javax.swing.JLabel monT;
    private javax.swing.JTextArea satBox;
    private javax.swing.JLabel satT;
    private javax.swing.JTextArea sunBox;
    private javax.swing.JLabel sunT;
    private javax.swing.JTextArea thuBox;
    private javax.swing.JLabel thuT;
    private javax.swing.JTextArea tueBox;
    private javax.swing.JLabel tueT;
    private javax.swing.JTextArea wedBox;
    private javax.swing.JLabel wedT;
    private javax.swing.JButton workBtn;
    // End of variables declaration//GEN-END:variables

    private static class DefaultTableMode1 {

        public DefaultTableMode1(String[][] data, String[] colums) {
        }
    }
}
